Repository MutopiaProject/MutopiaProject, pull requests merged in 2024-07, with the labels that each got.

#943 Prep 582
  ftp/AbtF/swallows/swallows.ly
  ftp/AdamsS/bluemtns/bluemtns.ly
  ftp/AscherJ/alice/alice.ly
  ftp/BachJS/BWV1056/arioso/arioso.ly
  ftp/BachJS/BWV248/Bach_BrichAn/Bach_BrichAn.ly
  ftp/BachJS/BWV277/Bach_ChristLag/Bach_ChristLag.ly
  ftp/BishopHR/homeshome/homeshome.ly
  ftp/CareyH/sally/sally.ly
  ftp/Claribel/oldsong/oldsong.ly
  ftp/DandrieuJ/Fugue_sur_l_Ave_maris_stella/Fugue_sur_l_Ave_maris_stella.ly
  ftp/GloverCW/thinkhome/thinkhome.ly
  ftp/GrignyNd/Grigny-Fugue_a_5/Grigny-Fugue_a_5.ly
  ftp/HandelGF/BWV351/LaRej/LaRej.ly
  ftp/HullahJ/fish/fish.ly
  ftp/KiallmarkGF/oakbucket/oakbucket.ly
  ftp/MooreT/lrose/lrose.ly
  ftp/MorelandC/oldshawl/oldshawl.ly
  ftp/MussorgskyM/nobm/nobm.ly
  ftp/RootGF/MusAirCh/MusAirCh.ly
  ftp/RootGF/chair/chair.ly
  ftp/RootGF/musicinair/musicinair.ly
  ftp/SanzG/sanz-1/sanz-1.ly
  ftp/SilcherF/loreley/loreley.ly
  ftp/TitelouzeJ/Veni_Creator-2e_verset/Veni_Creator-2e_verset.ly
  ftp/TitelouzeJ/Veni_Creator-3e_verset/Veni_Creator-3e_verset.ly
  ftp/TitelouzeJ/Veni_Creator-4e_verset/Veni_Creator-4e_verset.ly
Labels: Content-Update

#1036 Fixing typos (for Stemby), update mutopia header
  ftp/SittH/O32/Hans_Sitt-100_Etudes_Op32-Book1/Hans_Sitt-100_Etudes_Op32-Book1-lys/15.ly
  ftp/SittH/O32/Hans_Sitt-100_Etudes_Op32-Book1/Hans_Sitt-100_Etudes_Op32-Book1-lys/Hans_Sitt-100_Etudes_Op32-Book1.ly
Labels: Content-Update, Need-Feedback

#1082 Update Chopin O6, No1 to 2.18.2
  ftp/ChopinFF/O6/Mazurka-Op6-No1/Mazurka-Op6-No1.ly
Labels: Content-Update

#1087 Fixes and updates from Franck Decrock
  ftp/TarregaF/capricho-arabe/capricho-arabe.ly
Labels: Content-Update

#1106 Rachmaninoff Prelude in G minor: fix notes in RH of bar 4
  ftp/RachmaninoffS/O23/rach-prelude23-05/rach-prelude23-05.ly
Labels: Content-Update

#1109 Music fix and cleanup/update to LilyPond version 2.20.0
  ftp/BachJS/BWV938/bwv-938/bwv-938.ly
Labels: Content-Update

#1118 fix : A instead of B at bar number 6.
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/1-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/1-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/1-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/1.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/2-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/2-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/2-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/2.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/3-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/3-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/3-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/3.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/4-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/4-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/4-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/4.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/5-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/5-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/5-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/5.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/6-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/6-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/6-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/6.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/7-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/7-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/7-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/7.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/8-cello.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/8-viola.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/8-violin.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/8.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/header.ly
  ftp/BachJS/BWV1002/partita-1/partita-1-lys/solo-violin-partita-i.ly
Labels: Content-Update

#1116 Update debussy_Ste_Bergamesq_Clair.ly
  ftp/DebussyC/L75/debussy_Ste_Bergamesq_Clair/debussy_Ste_Bergamesq_Clair.ly
Labels: Content-Update

#1117 Update bach-praeludium-02.ly
  ftp/BachJS/BWV926/bach-praeludium-02/bach-praeludium-02.ly
Labels: Content-Update

#1120 Update no_2.ly
  ftp/SatieE/Gnossienne/no_2/no_2.ly
Labels: Content-Update

#1079 Prep PR #1065, new piece id 2248
  ftp/Rimsky-KorsakovN/PesnyaVaryazhskogoGostya/PesnyaVaryazhskogoGostya.ly
Labels: Content-Add
